[package]
name = "uuid_to_pokemon_cli"
version = "0.1.0"
authors = ["Clement Delafargue <clement@delafargue.name>"]

[dependencies]
uuid_to_pokemon = { version = "^0.2", path = "../lib" }
uuid = { version = "0.5", features = ["v4"] }
